"""empty message

Revision ID: 3e08f004fb06
Revises: ccf17d282ed1
Create Date: 2023-08-29 17:38:22.936630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e08f004fb06'
down_revision = 'ccf17d282ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saison', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('making', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('isprivat', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_recipe_isprivat'), ['isprivat'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_isprivat'))
        batch_op.drop_column('isprivat')
        batch_op.drop_column('making')
        batch_op.drop_column('saison')

    # ### end Alembic commands ###
