"""empty message

Revision ID: 959877d464ae
Revises: b9b36b432492
Create Date: 2023-09-01 11:56:16.294943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '959877d464ae'
down_revision = 'b9b36b432492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('subtext',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('saison',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('making',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('ingred1',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred2',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred3',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred4',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred5',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred6',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred7',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred8',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred10',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred11',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred12',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred13',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred14',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred15',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred16',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred17',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred18',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('ingred19',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('ingred19',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred18',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred17',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred16',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred15',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred14',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred13',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred12',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred11',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred10',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred8',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred7',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred6',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred5',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred4',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred3',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred2',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('ingred1',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('making',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('saison',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('subtext',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
