"""empty message

Revision ID: ccf17d282ed1
Revises: 
Create Date: 2023-08-29 17:28:18.928278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf17d282ed1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('subtext', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('ingred1', sa.String(length=32), nullable=True),
    sa.Column('ingred2', sa.String(length=32), nullable=True),
    sa.Column('ingred3', sa.String(length=32), nullable=True),
    sa.Column('ingred4', sa.String(length=32), nullable=True),
    sa.Column('ingred5', sa.String(length=32), nullable=True),
    sa.Column('ingred6', sa.String(length=32), nullable=True),
    sa.Column('ingred7', sa.String(length=32), nullable=True),
    sa.Column('ingred8', sa.String(length=32), nullable=True),
    sa.Column('ingred10', sa.String(length=32), nullable=True),
    sa.Column('ingred11', sa.String(length=32), nullable=True),
    sa.Column('ingred12', sa.String(length=32), nullable=True),
    sa.Column('ingred13', sa.String(length=32), nullable=True),
    sa.Column('ingred14', sa.String(length=32), nullable=True),
    sa.Column('ingred15', sa.String(length=32), nullable=True),
    sa.Column('ingred16', sa.String(length=32), nullable=True),
    sa.Column('ingred17', sa.String(length=32), nullable=True),
    sa.Column('ingred18', sa.String(length=32), nullable=True),
    sa.Column('ingred19', sa.String(length=32), nullable=True),
    sa.Column('ingred20', sa.String(length=32), nullable=True),
    sa.Column('steps1', sa.String(length=256), nullable=True),
    sa.Column('steps2', sa.String(length=256), nullable=True),
    sa.Column('steps3', sa.String(length=256), nullable=True),
    sa.Column('steps4', sa.String(length=256), nullable=True),
    sa.Column('steps5', sa.String(length=256), nullable=True),
    sa.Column('steps6', sa.String(length=256), nullable=True),
    sa.Column('steps7', sa.String(length=256), nullable=True),
    sa.Column('steps8', sa.String(length=256), nullable=True),
    sa.Column('steps9', sa.String(length=256), nullable=True),
    sa.Column('steps10', sa.String(length=256), nullable=True),
    sa.Column('steps11', sa.String(length=256), nullable=True),
    sa.Column('steps12', sa.String(length=256), nullable=True),
    sa.Column('steps13', sa.String(length=256), nullable=True),
    sa.Column('steps14', sa.String(length=256), nullable=True),
    sa.Column('steps15', sa.String(length=256), nullable=True),
    sa.Column('steps16', sa.String(length=256), nullable=True),
    sa.Column('steps17', sa.String(length=256), nullable=True),
    sa.Column('steps18', sa.String(length=256), nullable=True),
    sa.Column('steps19', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingred1'), ['ingred1'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred10'), ['ingred10'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred11'), ['ingred11'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred12'), ['ingred12'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred13'), ['ingred13'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred14'), ['ingred14'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred15'), ['ingred15'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred16'), ['ingred16'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred17'), ['ingred17'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred18'), ['ingred18'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred19'), ['ingred19'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred2'), ['ingred2'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred20'), ['ingred20'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred3'), ['ingred3'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred4'), ['ingred4'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred5'), ['ingred5'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred6'), ['ingred6'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred7'), ['ingred7'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingred8'), ['ingred8'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps1'), ['steps1'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps10'), ['steps10'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps11'), ['steps11'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps12'), ['steps12'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps13'), ['steps13'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps14'), ['steps14'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps15'), ['steps15'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps16'), ['steps16'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps17'), ['steps17'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps18'), ['steps18'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps19'), ['steps19'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps2'), ['steps2'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps3'), ['steps3'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps4'), ['steps4'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps5'), ['steps5'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps6'), ['steps6'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps7'), ['steps7'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps8'), ['steps8'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_steps9'), ['steps9'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_time'), ['time'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_timestamp'))
        batch_op.drop_index(batch_op.f('ix_recipe_time'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps9'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps8'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps7'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps6'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps5'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps4'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps3'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps2'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps19'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps18'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps17'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps16'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps15'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps14'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps13'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps12'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps11'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps10'))
        batch_op.drop_index(batch_op.f('ix_recipe_steps1'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred8'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred7'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred6'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred5'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred4'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred3'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred20'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred2'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred19'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred18'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred17'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred16'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred15'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred14'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred13'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred12'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred11'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred10'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingred1'))

    op.drop_table('recipe')
    # ### end Alembic commands ###
